<?php
require_once dirname(__FILE__) . '/ErrorHandler.php';

function getDBField(array $fieldSpecs, $apiFieldName)
{
    if (!array_key_exists($apiFieldName, $fieldSpecs)) {
        ErrorHandler::getHandler()->sendError(400, "Field name is invalid: $apiFieldName.",
            "Field name not in FIELD_SPECS: $apiFieldName.");
    }
    return $fieldSpecs[$apiFieldName]['column_name'];
}

/*
 * ENTITY_SPECS: defines the entities we are dealing with. The first one is the primary entity; the others are
 *              subentities.
 * entity_name: name for this entity type. Used internal for an individual entity. Used externally as the name for
 *              individual units of this entity
 * group_name:  plural name for the group. Used internal for aggregating into groups and for external output.
 * keyId:       The field in the FIELD_SPECS that is a unique identifier. Could be blank for those entity types
 *              that are not really considered individual entities, but are more of a list of grouped attributes
 * join:        The SQL join statement that will bring in the data for this entity type when connected with the
 *              primary entity's JOIN statement. Note: these must be able to be used in aggregate with all the
 *              other joins in the ENTITY_SPECS, so any duplicate joins to the same table must use a unique
 *              alias for that table.
*/

$PATENT_ENTITY_SPECS = array(
    array('entity_name'=>'patent', 'group_name'=>'patents', 'keyId'=>'patent_id', 'join'=>'patent'),
    array('entity_name'=>'inventor', 'group_name'=>'inventors', 'keyId'=>'inventor_key_id', 'join'=>'left outer JOIN patent_inventor ON patent.patent_id=patent_inventor.patent_id left outer JOIN inventor ON patent_inventor.inventor_id=inventor.inventor_id left outer join inventor_location ON inventor.inventor_id=inventor_location.inventor_id'),
    array('entity_name'=>'assignee', 'group_name'=>'assignees', 'keyId'=>'assignee_key_id', 'join'=>'left outer join patent_assignee on patent.patent_id=patent_assignee.patent_id left outer join assignee ON patent_assignee.assignee_id=assignee.assignee_id left outer JOIN assignee_location on assignee.assignee_id=assignee_location.assignee_id'),
    array('entity_name'=>'application', 'group_name'=>'applications', 'keyId'=>'app_id', 'join'=>'left outer join application on patent.patent_id=application.patent_id'),
    array('entity_name'=>'ipc', 'group_name'=>'IPCs', 'keyId'=>'', 'join'=>'left outer join ipcr on patent.patent_id=ipcr.patent_id'),
    array('entity_name'=>'applicationcitation', 'group_name'=>'application_citations', 'keyId'=>'', 'join'=>'left outer join usapplicationcitation on patent.patent_id=usapplicationcitation.citing_patent_id left outer join application appcit_app on usapplicationcitation.cited_application_id=appcit_app.application_id'),
    array('entity_name'=>'cited_patent', 'group_name'=>'cited_patents', 'keyId'=>'', 'join'=>'left outer join uspatentcitation as patentcit_fromciting_tocited on patent.patent_id=patentcit_fromciting_tocited.citing_patent_id left outer join patent as citedpatent on patentcit_fromciting_tocited.cited_patent_id=citedpatent.patent_id'),
    array('entity_name'=>'citedby_patent', 'group_name'=>'citedby_patents', 'keyId'=>'', 'join'=>'left outer join uspatentcitation as patentcit_fromcited_tociting on patent.patent_id=patentcit_fromcited_tociting.cited_patent_id left outer join patent as citingpatent on patentcit_fromcited_tociting.citing_patent_id=citingpatent.patent_id'),
    array('entity_name'=>'uspc', 'group_name'=>'uspcs', 'keyId'=>'', 'join'=>'left outer join uspc_current on patent.patent_id=uspc_current.patent_id'),
    array('entity_name'=>'cpc', 'group_name'=>'cpcs', 'keyId'=>'', 'join'=>'left outer join cpc_current on patent.patent_id=cpc_current.patent_id')
);

/*
 * FIELD_SPECS:     defines the fields available for an entity, in what table/column it can be found, and other
 *                  attributes of the field/column.
 * key:             the unique internal and external name for the field
 * entity_name:     the name of the parent entity; must match an 'entity_name' in the ENTITY_SPECS
 * table:           the DB table that contains this field. This table must be in the 'join' statement for the entity
 *                  type in the ENTITY_SPECS
 * column_name:     the SQL name of the column in table
 * datatype:        One of 'string', 'int', 'float', 'date', 'fulltext'
 * sort:            'y' or 'n' depending on if the primary entity can be sorted on this field. Only set to 'y' when
 *                  the field would be unique for that primary entity. If the field is part of a one-to-many, then
 *                  it must be 'n'; otherwise the return results would likely get mixed up.
 */

$PATENT_FIELD_SPECS = array
(
    'app_country' => array('entity_name'=>'application', 'column_name' => 'application.country', 'datatype' => 'string', 'sort' => 'y'),
    'app_date' => array('entity_name'=>'application', 'column_name' => 'application.date', 'datatype' => 'date', 'sort' => 'y'),
    'app_id' => array('entity_name'=>'application', 'column_name' => 'application.application_id', 'datatype' => 'string', 'sort' => 'Y'),
    'app_number' => array('entity_name'=>'application', 'column_name' => 'application.number', 'datatype' => 'string', 'sort' => 'y'),
    'app_type' => array('entity_name'=>'application', 'column_name' => 'application.type', 'datatype' => 'string', 'sort' => 'y'),
    'appcit_app_number' => array('entity_name'=>'applicationcitation', 'column_name' => 'appcit_app.number', 'datatype' => 'string', 'sort' => 'n'),
    'appcit_category' => array('entity_name'=>'applicationcitation', 'column_name' => 'usapplicationcitation.category', 'datatype' => 'string', 'sort' => 'n'),
    'appcit_date' => array('entity_name'=>'applicationcitation', 'column_name' => 'usapplicationcitation.date', 'datatype' => 'date', 'sort' => 'n'),
    'appcit_kind' => array('entity_name'=>'applicationcitation', 'column_name' => 'usapplicationcitation.kind', 'datatype' => 'string', 'sort' => 'n'),
    'appcit_name' => array('entity_name'=>'applicationcitation', 'column_name' => 'usapplicationcitation.name', 'datatype' => 'string', 'sort' => 'n'),
    'appcit_sequence' => array('entity_name'=>'applicationcitation', 'column_name' => 'usapplicationcitation.sequence', 'datatype' => 'int', 'sort' => 'n'),
    'assignee_city' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.city', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_country' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.country', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_first_name' => array('entity_name'=>'assignee', 'column_name' => 'assignee.name_first', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_id' => array('entity_name'=>'assignee', 'column_name' => 'assignee.persistent_assignee_id', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_key_id' => array('entity_name'=>'assignee', 'column_name' => 'assignee.assignee_id', 'datatype' => 'int', 'sort' => 'n'),
    'assignee_lastknown_city' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_city', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_lastknown_country' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_country', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_lastknown_latitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_latitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_lastknown_longitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_longitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_lastknown_state' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_state', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_last_name' => array('entity_name'=>'assignee', 'column_name' => 'assignee.name_last', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_latitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.latitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_longitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.longitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_num_patents' => array('entity_name'=>'assignee', 'column_name' => 'assignee.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'assignee_organization' => array('entity_name'=>'assignee', 'column_name' => 'assignee.organization', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_state' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.state', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_type' => array('entity_name'=>'assignee', 'column_name' => 'assignee.type', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_years_active' => array('entity_name'=>'assignee', 'column_name' => 'concat(year(assignee.first_seen_date),\'-\',year(assignee.last_seen_date))', 'datatype' => 'string', 'sort' => 'n'),
    'citedby_patent_category' => array('entity_name'=>'citedby_patent', 'column_name' => 'patentcit_fromcited_tociting.category', 'datatype' => 'string', 'sort' => 'n'),
    'citedby_patent_date' => array('entity_name'=>'citedby_patent', 'column_name' => 'citingpatent.date', 'datatype' => 'date', 'sort' => 'n'),
    'citedby_patent_kind' => array('entity_name'=>'citedby_patent', 'column_name' => 'citingpatent.kind', 'datatype' => 'string', 'sort' => 'n'),
    'citedby_patent_number' => array('entity_name'=>'citedby_patent', 'column_name' => 'citingpatent.number', 'datatype' => 'string', 'sort' => 'n'),
    'citedby_patent_title' => array('entity_name'=>'citedby_patent', 'column_name' => 'citingpatent.title', 'datatype' => 'string', 'sort' => 'n'),
    'cited_patent_category' => array('entity_name'=>'cited_patent', 'column_name' => 'patentcit_fromciting_tocited.category', 'datatype' => 'string', 'sort' => 'n'),
    'cited_patent_date' => array('entity_name'=>'cited_patent', 'column_name' => 'citedpatent.date', 'datatype' => 'date', 'sort' => 'n'),
    'cited_patent_kind' => array('entity_name'=>'cited_patent', 'column_name' => 'citedpatent.kind', 'datatype' => 'string', 'sort' => 'n'),
    'cited_patent_number' => array('entity_name'=>'cited_patent', 'column_name' => 'citedpatent.number', 'datatype' => 'string', 'sort' => 'n'),
    'cited_patent_sequence' => array('entity_name'=>'cited_patent', 'column_name' => 'patentcit_fromciting_tocited.sequence', 'datatype' => 'int', 'sort' => 'n'),
    'cited_patent_title' => array('entity_name'=>'cited_patent', 'column_name' => 'citedpatent.title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_category' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.category', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_group_id' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.group_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_group_title' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.group_title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_num_assignees' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.num_assignees', 'datatype' => 'int', 'sort' => 'n'),
    'cpc_num_inventors' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.num_inventors', 'datatype' => 'int', 'sort' => 'n'),
    'cpc_num_patents' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'cpc_sequence' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.sequence', 'datatype' => 'int', 'sort' => 'n'),
    'cpc_section_d' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.section_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subgroup_id' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subgroup_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subgroup_title' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subgroup_title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subsection_id' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subsection_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subsection_title' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subsection_title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_years_active' => array('entity_name'=>'cpc', 'column_name' => 'concat(year(cpc_current.first_seen_date),\'-\',year(cpc_current.last_seen_date))', 'datatype' => 'int', 'sort' => 'n'),
    'inventor_city' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.city', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_country' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.country', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_first_name' => array('entity_name'=>'inventor', 'column_name' => 'inventor.name_first', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_id' => array('entity_name'=>'inventor', 'column_name' => 'inventor.persistent_inventor_id', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_key_id' => array('entity_name'=>'inventor', 'column_name' => 'inventor.inventor_id', 'datatype' => 'int', 'sort' => 'n'),
    'inventor_last_name' => array('entity_name'=>'inventor', 'column_name' => 'inventor.name_last', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_lastknown_city' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_city', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_lastknown_country' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_country', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_lastknown_latitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_latitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_lastknown_longitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_longitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_lastknown_state' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_state', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_latitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.latitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_longitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.longitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_num_patents' => array('entity_name'=>'inventor', 'column_name' => 'inventor.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'inventor_state' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.state', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_years_active' => array('entity_name'=>'inventor', 'column_name' => 'concat(year(inventor.first_seen_date),\'-\',year(inventor.last_seen_date))', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_action_date' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.action_date', 'datatype' => 'date', 'sort' => 'n'),
    'ipc_class' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.ipc_class', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_classification_data_source' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.classification_data_source', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_classification_value' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.classification_value', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_main_group' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.main_group', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_num_assignees' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.num_assignees', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_num_inventors' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.num_inventors', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_section' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.section', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_sequence' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.sequence', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_subclass' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.subclass', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_subgroup' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.subgroup', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_symbol_position' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.symbol_position', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_version_indicator' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.ipc_version_indicator', 'datatype' => 'date', 'sort' => 'n'),
    'ipc_years_active' => array('entity_name'=>'ipc', 'column_name' => 'concat(year(ipcr.first_seen_date),\'-\',year(ipcr.last_seen_date))', 'datatype' => 'int', 'sort' => 'n'),
    'patent_abstract' => array('entity_name'=>'patent', 'column_name' => 'patent.abstract', 'datatype' => 'fulltext', 'sort' => 'n'),
    'patent_date' => array('entity_name'=>'patent', 'column_name' => 'patent.date', 'datatype' => 'date', 'sort' => 'y'),
    'patent_firstnamed_city' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_city', 'datatype' => 'string', 'sort' => 'y'),
    'patent_firstnamed_country' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_country', 'datatype' => 'string', 'sort' => 'y'),
    'patent_firstnamed_latitude' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_latitude', 'datatype' => 'float', 'sort' => 'y'),
    'patent_firstnamed_longitude' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_longitude', 'datatype' => 'float', 'sort' => 'y'),
    'patent_firstnamed_state' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_state', 'datatype' => 'string', 'sort' => 'y'),
    'patent_id' => array('entity_name'=>'patent', 'column_name' => 'patent.patent_id', 'datatype' => 'string', 'sort' => 'y'),
    'patent_kind' => array('entity_name'=>'patent', 'column_name' => 'patent.kind', 'datatype' => 'string', 'sort' => 'y'),
    'patent_num_cited_by_us_patents' => array('entity_name'=>'patent', 'column_name' => 'patent.num_times_cited_by_us_patents', 'datatype' => 'int', 'sort' => 'y'),
    'patent_num_combined_citations' => array('entity_name'=>'patent', 'column_name' => 'patent.num_total_documents_cited', 'datatype' => 'int', 'sort' => 'y'),
    'patent_num_foreign_citations' => array('entity_name'=>'patent', 'column_name' => 'patent.num_foreign_documents_cited', 'datatype' => 'int', 'sort' => 'y'),
    'patent_num_us_application_citations' => array('entity_name'=>'patent', 'column_name' => 'patent.num_us_applications_cited', 'datatype' => 'int', 'sort' => 'y'),
    'patent_num_us_patent_citations' => array('entity_name'=>'patent', 'column_name' => 'patent.num_us_patents_cited', 'datatype' => 'int', 'sort' => 'y'),
    'patent_num_claims' => array('entity_name'=>'patent', 'column_name' => 'patent.num_claims', 'datatype' => 'int', 'sort' => 'y'),
    'patent_number' => array('entity_name'=>'patent', 'column_name' => 'patent.number', 'datatype' => 'string', 'sort' => 'y'),
    'patent_title' => array('entity_name'=>'patent', 'column_name' => 'patent.title', 'datatype' => 'fulltext', 'sort' => 'y'),
    'patent_type' => array('entity_name'=>'patent', 'column_name' => 'patent.type', 'datatype' => 'string', 'sort' => 'y'),
    'uspc_mainclass_id' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.mainclass_id', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_mainclass_title' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.mainclass_title', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_num_assignees' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.num_assignees', 'datatype' => 'int', 'sort' => 'n'),
    'uspc_num_inventors' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.num_inventors', 'datatype' => 'int', 'sort' => 'n'),
    'uspc_num_patents' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'uspc_sequence' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.sequence', 'datatype' => 'int', 'sort' => 'n'),
    'uspc_subclass_id' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.subclass_id', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_subclass_title' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.subclass_title', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_years_active' => array('entity_name'=>'uspc', 'column_name' => 'concat(year(uspc_current.first_seen_date),\'-\',year(uspc_current.last_seen_date))', 'datatype' => 'int', 'sort' => 'n')

);

$INVENTOR_ENTITY_SPECS = array(
    array('entity_name'=>'inventor', 'group_name'=>'inventors', 'keyId'=>'inventor_key_id', 'join'=>' inventor left outer JOIN inventor_location on inventor.inventor_id=inventor_location.inventor_id left outer join patent_inventor on inventor.inventor_id=patent_inventor.inventor_id'),
    array('entity_name'=>'patent', 'group_name'=>'patents', 'keyId'=>'patent_id', 'join'=>'left outer JOIN patent on patent_inventor.patent_id=patent.patent_id'),
    array('entity_name'=>'assignee', 'group_name'=>'assignees', 'keyId'=>'assignee_key_id', 'join'=>'left outer join patent_assignee on patent_inventor.patent_id=patent_assignee.patent_id left outer join assignee ON patent_assignee.assignee_id=assignee.assignee_id left outer JOIN assignee_location on assignee.assignee_id=assignee_location.assignee_id'),
    array('entity_name'=>'application', 'group_name'=>'applications', 'keyId'=>'app_id', 'join'=>'left outer join application on patent_inventor.patent_id=application.patent_id'),
    array('entity_name'=>'ipc', 'group_name'=>'IPCs', 'keyId'=>'', 'join'=>'left outer join ipcr on patent_inventor.patent_id=ipcr.patent_id'),
    array('entity_name'=>'uspc', 'group_name'=>'uspcs', 'keyId'=>'', 'join'=>'left outer join uspc_current on patent_inventor.patent_id=uspc_current.patent_id'),
    array('entity_name'=>'cpc', 'group_name'=>'cpcs', 'keyId'=>'', 'join'=>'left outer join cpc_current on patent_inventor.patent_id=cpc_current.patent_id')
);

$INVENTOR_FIELD_SPECS = array
(
    'app_country' => array('entity_name'=>'application', 'column_name' => 'application.country', 'datatype' => 'string', 'sort' => 'n'),
    'app_date' => array('entity_name'=>'application', 'column_name' => 'application.date', 'datatype' => 'date', 'sort' => 'n'),
    'app_id' => array('entity_name'=>'application', 'column_name' => 'application.application_id', 'datatype' => 'string', 'sort' => 'n'),
    'app_number' => array('entity_name'=>'application', 'column_name' => 'application.number', 'datatype' => 'string', 'sort' => 'n'),
    'app_type' => array('entity_name'=>'application', 'column_name' => 'application.type', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_city' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.city', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_country' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.country', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_first_name' => array('entity_name'=>'assignee', 'column_name' => 'assignee.name_first', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_id' => array('entity_name'=>'assignee', 'column_name' => 'assignee.persistent_assignee_id', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_key_id' => array('entity_name'=>'assignee', 'column_name' => 'assignee.assignee_id', 'datatype' => 'int', 'sort' => 'n'),
    'assignee_lastknown_city' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_city', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_lastknown_country' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_country', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_lastknown_latitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_latitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_lastknown_longitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_longitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_lastknown_state' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_state', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_last_name' => array('entity_name'=>'assignee', 'column_name' => 'assignee.name_last', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_latitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.latitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_longitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.longitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_num_patents' => array('entity_name'=>'assignee', 'column_name' => 'assignee.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'assignee_organization' => array('entity_name'=>'assignee', 'column_name' => 'assignee.organization', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_state' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.state', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_type' => array('entity_name'=>'assignee', 'column_name' => 'assignee.type', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_years_active' => array('entity_name'=>'assignee', 'column_name' => 'concat(year(assignee.first_seen_date),\'-\',year(assignee.last_seen_date))', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_category' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.category', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_group_id' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.group_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_group_title' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.group_title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_num_assignees' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.num_assignees', 'datatype' => 'int', 'sort' => 'n'),
    'cpc_num_inventors' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.num_inventors', 'datatype' => 'int', 'sort' => 'n'),
    'cpc_num_patents' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'cpc_section_d' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.section_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subgroup_id' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subgroup_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subgroup_title' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subgroup_title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subsection_id' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subsection_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subsection_title' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subsection_title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_years_active' => array('entity_name'=>'cpc', 'column_name' => 'concat(year(cpc_current.first_seen_date),\'-\',year(cpc_current.last_seen_date))', 'datatype' => 'int', 'sort' => 'n'),
    'inventor_city' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.city', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_country' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.country', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_first_name' => array('entity_name'=>'inventor', 'column_name' => 'inventor.name_first', 'datatype' => 'string', 'sort' => 'y'),
    'inventor_id' => array('entity_name'=>'inventor', 'column_name' => 'inventor.persistent_inventor_id', 'datatype' => 'string', 'sort' => 'y'),
    'inventor_key_id' => array('entity_name'=>'inventor', 'column_name' => 'inventor.inventor_id', 'datatype' => 'int', 'sort' => 'y'),
    'inventor_last_name' => array('entity_name'=>'inventor', 'column_name' => 'inventor.name_last', 'datatype' => 'string', 'sort' => 'y'),
    'inventor_lastknown_city' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_city', 'datatype' => 'string', 'sort' => 'y'),
    'inventor_lastknown_country' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_country', 'datatype' => 'string', 'sort' => 'y'),
    'inventor_lastknown_latitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_latitude', 'datatype' => 'float', 'sort' => 'y'),
    'inventor_lastknown_longitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_longitude', 'datatype' => 'float', 'sort' => 'y'),
    'inventor_lastknown_state' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_state', 'datatype' => 'string', 'sort' => 'y'),
    'inventor_latitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.latitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_longitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.longitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_num_patents' => array('entity_name'=>'inventor', 'column_name' => 'inventor.num_patents', 'datatype' => 'int', 'sort' => 'y'),
    'inventor_state' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.state', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_years_active' => array('entity_name'=>'inventor', 'column_name' => 'concat(year(inventor.first_seen_date),\'-\',year(inventor.last_seen_date))', 'datatype' => 'int', 'sort' => 'y'),
    'ipc_action_date' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.action_date', 'datatype' => 'date', 'sort' => 'n'),
    'ipc_class' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.ipc_class', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_classification_data_source' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.classification_data_source', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_classification_value' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.classification_value', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_main_group' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.main_group', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_num_assignees' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.num_assignees', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_num_inventors' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.num_inventors', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_section' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.section', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_subclass' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.subclass', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_subgroup' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.subgroup', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_symbol_position' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.symbol_position', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_version_indicator' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.ipc_version_indicator', 'datatype' => 'date', 'sort' => 'n'),
    'ipc_years_active' => array('entity_name'=>'ipc', 'column_name' => 'concat(year(ipcr.first_seen_date),\'-\',year(ipcr.last_seen_date))', 'datatype' => 'int', 'sort' => 'n'),
    'patent_abstract' => array('entity_name'=>'patent', 'column_name' => 'patent.abstract', 'datatype' => 'fulltext', 'sort' => 'n'),
    'patent_date' => array('entity_name'=>'patent', 'column_name' => 'patent.date', 'datatype' => 'date', 'sort' => 'n'),
    'patent_firstnamed_city' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_city', 'datatype' => 'string', 'sort' => 'n'),
    'patent_firstnamed_country' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_country', 'datatype' => 'string', 'sort' => 'n'),
    'patent_firstnamed_latitude' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_latitude', 'datatype' => 'float', 'sort' => 'n'),
    'patent_firstnamed_longitude' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_longitude', 'datatype' => 'float', 'sort' => 'n'),
    'patent_firstnamed_state' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_state', 'datatype' => 'string', 'sort' => 'n'),
    'patent_id' => array('entity_name'=>'patent', 'column_name' => 'patent.patent_id', 'datatype' => 'string', 'sort' => 'n'),
    'patent_kind' => array('entity_name'=>'patent', 'column_name' => 'patent.kind', 'datatype' => 'string', 'sort' => 'n'),
    'patent_num_citations' => array('entity_name'=>'patent', 'column_name' => 'patent.num_us_patents_cited', 'datatype' => 'int', 'sort' => 'n'),
    'patent_num_claims' => array('entity_name'=>'patent', 'column_name' => 'patent.num_claims', 'datatype' => 'int', 'sort' => 'n'),
    'patent_number' => array('entity_name'=>'patent', 'column_name' => 'patent.number', 'datatype' => 'string', 'sort' => 'n'),
    'patent_title' => array('entity_name'=>'patent', 'column_name' => 'patent.title', 'datatype' => 'fulltext', 'sort' => 'n'),
    'patent_type' => array('entity_name'=>'patent', 'column_name' => 'patent.type', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_mainclass_id' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.mainclass_id', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_mainclass_title' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.mainclass_title', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_num_assignees' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.num_assignees', 'datatype' => 'int', 'sort' => 'n'),
    'uspc_num_inventors' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.num_inventors', 'datatype' => 'int', 'sort' => 'n'),
    'uspc_num_patents' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'uspc_subclass_id' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.subclass_id', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_subclass_title' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.subclass_title', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_years_active' => array('entity_name'=>'uspc', 'column_name' => 'concat(year(uspc_current.first_seen_date),\'-\',year(uspc_current.last_seen_date))', 'datatype' => 'int', 'sort' => 'n')

);


$ASSIGNEE_ENTITY_SPECS = array(
    array('entity_name'=>'assignee', 'group_name'=>'assignees', 'keyId'=>'assignee_key_id', 'join'=>' assignee left outer JOIN assignee_location on assignee.assignee_id=assignee_location.assignee_id left outer join patent_assignee on assignee.assignee_id=patent_assignee.assignee_id'),
    array('entity_name'=>'patent', 'group_name'=>'patents', 'keyId'=>'patent_id', 'join'=>'left outer JOIN patent on patent_assignee.patent_id=patent.patent_id'),
    array('entity_name'=>'inventor', 'group_name'=>'inventors', 'keyId'=>'inventor_key_id', 'join'=>'left outer join patent_inventor on patent_assignee.patent_id=patent_inventor.patent_id left outer join inventor ON patent_inventor.inventor_id=inventor.inventor_id left outer JOIN inventor_location on inventor.inventor_id=inventor_location.inventor_id'),
    array('entity_name'=>'application', 'group_name'=>'applications', 'keyId'=>'app_id', 'join'=>'left outer join application on patent_assignee.patent_id=application.patent_id'),
    array('entity_name'=>'ipc', 'group_name'=>'IPCs', 'keyId'=>'', 'join'=>'left outer join ipcr on patent_assignee.patent_id=ipcr.patent_id'),
    array('entity_name'=>'uspc', 'group_name'=>'uspcs', 'keyId'=>'', 'join'=>'left outer join uspc_current on patent_assignee.patent_id=uspc_current.patent_id'),
    array('entity_name'=>'cpc', 'group_name'=>'cpcs', 'keyId'=>'', 'join'=>'left outer join cpc_current on patent_assignee.patent_id=cpc_current.patent_id')
);

$ASSIGNEE_FIELD_SPECS = array
(
    'app_country' => array('entity_name'=>'application', 'column_name' => 'application.country', 'datatype' => 'string', 'sort' => 'n'),
    'app_date' => array('entity_name'=>'application', 'column_name' => 'application.date', 'datatype' => 'date', 'sort' => 'n'),
    'app_id' => array('entity_name'=>'application', 'column_name' => 'application.application_id', 'datatype' => 'string', 'sort' => 'n'),
    'app_number' => array('entity_name'=>'application', 'column_name' => 'application.number', 'datatype' => 'string', 'sort' => 'n'),
    'app_type' => array('entity_name'=>'application', 'column_name' => 'application.type', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_city' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.city', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_country' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.country', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_first_name' => array('entity_name'=>'assignee', 'column_name' => 'assignee.name_first', 'datatype' => 'string', 'sort' => 'y'),
    'assignee_id' => array('entity_name'=>'assignee', 'column_name' => 'assignee.persistent_assignee_id', 'datatype' => 'string', 'sort' => 'y'),
    'assignee_key_id' => array('entity_name'=>'assignee', 'column_name' => 'assignee.assignee_id', 'datatype' => 'int', 'sort' => 'y'),
    'assignee_lastknown_city' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_city', 'datatype' => 'string', 'sort' => 'y'),
    'assignee_lastknown_country' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_country', 'datatype' => 'string', 'sort' => 'y'),
    'assignee_lastknown_latitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_latitude', 'datatype' => 'float', 'sort' => 'y'),
    'assignee_lastknown_longitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_longitude', 'datatype' => 'float', 'sort' => 'y'),
    'assignee_lastknown_state' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_state', 'datatype' => 'string', 'sort' => 'y'),
    'assignee_last_name' => array('entity_name'=>'assignee', 'column_name' => 'assignee.name_last', 'datatype' => 'string', 'sort' => 'y'),
    'assignee_latitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.latitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_longitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.longitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_num_patents' => array('entity_name'=>'assignee', 'column_name' => 'assignee.num_patents', 'datatype' => 'int', 'sort' => 'y'),
    'assignee_organization' => array('entity_name'=>'assignee', 'column_name' => 'assignee.organization', 'datatype' => 'string', 'sort' => 'y'),
    'assignee_state' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.state', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_type' => array('entity_name'=>'assignee', 'column_name' => 'assignee.type', 'datatype' => 'string', 'sort' => 'y'),
    'assignee_years_active' => array('entity_name'=>'assignee', 'column_name' => 'concat(year(assignee.first_seen_date),\'-\',year(assignee.last_seen_date))', 'datatype' => 'string', 'sort' => 'y'),
    'inventor_city' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.city', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_group_id' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.group_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_group_title' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.group_title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_num_assignees' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.num_assignees', 'datatype' => 'int', 'sort' => 'n'),
    'cpc_num_inventors' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.num_inventors', 'datatype' => 'int', 'sort' => 'n'),
    'cpc_num_patents' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'cpc_section_d' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.section_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subgroup_id' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subgroup_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subgroup_title' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subgroup_title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subsection_id' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subsection_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subsection_title' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subsection_title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_years_active' => array('entity_name'=>'cpc', 'column_name' => 'concat(year(cpc_current.first_seen_date),\'-\',year(cpc_current.last_seen_date))', 'datatype' => 'int', 'sort' => 'n'),
    'inventor_country' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.country', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_first_name' => array('entity_name'=>'inventor', 'column_name' => 'inventor.name_first', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_id' => array('entity_name'=>'inventor', 'column_name' => 'inventor.persistent_inventor_id', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_key_id' => array('entity_name'=>'inventor', 'column_name' => 'inventor.inventor_id', 'datatype' => 'int', 'sort' => 'n'),
    'inventor_last_name' => array('entity_name'=>'inventor', 'column_name' => 'inventor.name_last', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_lastknown_city' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_city', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_lastknown_country' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_country', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_lastknown_latitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_latitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_lastknown_longitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_longitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_lastknown_state' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_state', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_latitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.latitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_longitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.longitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_num_patents' => array('entity_name'=>'inventor', 'column_name' => 'inventor.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'inventor_state' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.state', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_years_active' => array('entity_name'=>'inventor', 'column_name' => 'concat(year(inventor.first_seen_date),\'-\',year(inventor.last_seen_date))', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_action_date' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.action_date', 'datatype' => 'date', 'sort' => 'n'),
    'ipc_class' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.ipc_class', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_classification_data_source' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.classification_data_source', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_classification_value' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.classification_value', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_main_group' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.main_group', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_num_assignees' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.num_assignees', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_num_inventors' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.num_inventors', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_section' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.section', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_subclass' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.subclass', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_subgroup' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.subgroup', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_symbol_position' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.symbol_position', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_version_indicator' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.ipc_version_indicator', 'datatype' => 'date', 'sort' => 'n'),
    'ipc_years_active' => array('entity_name'=>'ipc', 'column_name' => 'concat(year(ipcr.first_seen_date),\'-\',year(ipcr.last_seen_date))', 'datatype' => 'int', 'sort' => 'n'),
    'patent_abstract' => array('entity_name'=>'patent', 'column_name' => 'patent.abstract', 'datatype' => 'fulltext', 'sort' => 'n'),
    'patent_date' => array('entity_name'=>'patent', 'column_name' => 'patent.date', 'datatype' => 'date', 'sort' => 'n'),
    'patent_firstnamed_city' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_city', 'datatype' => 'string', 'sort' => 'n'),
    'patent_firstnamed_country' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_country', 'datatype' => 'string', 'sort' => 'n'),
    'patent_firstnamed_latitude' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_latitude', 'datatype' => 'float', 'sort' => 'n'),
    'patent_firstnamed_longitude' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_longitude', 'datatype' => 'float', 'sort' => 'n'),
    'patent_firstnamed_state' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_state', 'datatype' => 'string', 'sort' => 'n'),
    'patent_id' => array('entity_name'=>'patent', 'column_name' => 'patent.patent_id', 'datatype' => 'string', 'sort' => 'n'),
    'patent_kind' => array('entity_name'=>'patent', 'column_name' => 'patent.kind', 'datatype' => 'string', 'sort' => 'n'),
    'patent_num_citations' => array('entity_name'=>'patent', 'column_name' => 'patent.num_us_patents_cited', 'datatype' => 'int', 'sort' => 'n'),
    'patent_num_claims' => array('entity_name'=>'patent', 'column_name' => 'patent.num_claims', 'datatype' => 'int', 'sort' => 'n'),
    'patent_number' => array('entity_name'=>'patent', 'column_name' => 'patent.number', 'datatype' => 'string', 'sort' => 'n'),
    'patent_title' => array('entity_name'=>'patent', 'column_name' => 'patent.title', 'datatype' => 'fulltext', 'sort' => 'n'),
    'patent_type' => array('entity_name'=>'patent', 'column_name' => 'patent.type', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_mainclass_id' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.mainclass_id', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_mainclass_title' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.mainclass_title', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_num_assignees' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.num_assignees', 'datatype' => 'int', 'sort' => 'n'),
    'uspc_num_inventors' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.num_inventors', 'datatype' => 'int', 'sort' => 'n'),
    'uspc_num_patents' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'uspc_subclass_id' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.subclass_id', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_subclass_title' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.subclass_title', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_years_active' => array('entity_name'=>'uspc', 'column_name' => 'concat(year(uspc_current.first_seen_date),\'-\',year(uspc_current.last_seen_date))', 'datatype' => 'int', 'sort' => 'n')

);


$CPC_ENTITY_SPECS = array(
    array('entity_name'=>'cpc_subsection', 'group_name'=>'cpc_subsections', 'keyId'=>'cpc_subsection_id', 'join'=>'cpc_current'),
    array('entity_name'=>'cpc_subgroup', 'group_name'=>'cpc_subgroups', 'keyId'=>'cpc_subgroup_id', 'join'=>''),
    array('entity_name'=>'assignee', 'group_name'=>'assignees', 'keyId'=>'assignee_key_id', 'join'=>' left outer join patent_assignee on cpc_current.patent_id=patent_assignee.patent_id left outer JOIN assignee on patent_assignee.assignee_id=assignee.assignee_id left outer JOIN assignee_location on assignee.assignee_id=assignee_location.assignee_id'),
    array('entity_name'=>'patent', 'group_name'=>'patents', 'keyId'=>'patent_id', 'join'=>'left outer JOIN patent on cpc_current.patent_id=patent.patent_id'),
    array('entity_name'=>'inventor', 'group_name'=>'inventors', 'keyId'=>'inventor_key_id', 'join'=>'left outer join patent_inventor on cpc_current.patent_id=patent_inventor.patent_id left outer join inventor ON patent_inventor.inventor_id=inventor.inventor_id left outer JOIN inventor_location on inventor.inventor_id=inventor_location.inventor_id'),
    array('entity_name'=>'application', 'group_name'=>'applications', 'keyId'=>'app_id', 'join'=>'left outer join application on cpc_current.patent_id=application.patent_id'),
    array('entity_name'=>'ipc', 'group_name'=>'IPCs', 'keyId'=>'', 'join'=>'left outer join ipcr on cpc_current.patent_id=ipcr.patent_id'),
    array('entity_name'=>'uspc', 'group_name'=>'uspcs', 'keyId'=>'', 'join'=>'left outer join uspc_current on cpc_current.patent_id=uspc_current.patent_id')
);

$CPC_FIELD_SPECS = array
(
    'app_country' => array('entity_name'=>'application', 'column_name' => 'application.country', 'datatype' => 'string', 'sort' => 'n'),
    'app_date' => array('entity_name'=>'application', 'column_name' => 'application.date', 'datatype' => 'date', 'sort' => 'n'),
    'app_id' => array('entity_name'=>'application', 'column_name' => 'application.application_id', 'datatype' => 'string', 'sort' => 'n'),
    'app_number' => array('entity_name'=>'application', 'column_name' => 'application.number', 'datatype' => 'string', 'sort' => 'n'),
    'app_type' => array('entity_name'=>'application', 'column_name' => 'application.type', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_city' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.city', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_country' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.country', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_first_name' => array('entity_name'=>'assignee', 'column_name' => 'assignee.name_first', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_id' => array('entity_name'=>'assignee', 'column_name' => 'assignee.persistent_assignee_id', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_key_id' => array('entity_name'=>'assignee', 'column_name' => 'assignee.assignee_id', 'datatype' => 'int', 'sort' => 'n'),
    'assignee_lastknown_city' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_city', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_lastknown_country' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_country', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_lastknown_latitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_latitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_lastknown_longitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_longitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_lastknown_state' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_state', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_last_name' => array('entity_name'=>'assignee', 'column_name' => 'assignee.name_last', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_latitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.latitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_longitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.longitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_num_patents' => array('entity_name'=>'assignee', 'column_name' => 'assignee.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'assignee_organization' => array('entity_name'=>'assignee', 'column_name' => 'assignee.organization', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_state' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.state', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_type' => array('entity_name'=>'assignee', 'column_name' => 'assignee.type', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_years_active' => array('entity_name'=>'assignee', 'column_name' => 'concat(year(assignee.first_seen_date),\'-\',year(assignee.last_seen_date))', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_city' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.city', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_group_id' => array('entity_name'=>'cpc_subgroup', 'column_name' => 'cpc_current.group_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_group_title' => array('entity_name'=>'cpc_subgroup', 'column_name' => 'cpc_current.group_title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_num_assignees' => array('entity_name'=>'cpc_subsection', 'column_name' => 'cpc_current.num_assignees', 'datatype' => 'int', 'sort' => 'y'),
    'cpc_num_inventors' => array('entity_name'=>'cpc_subsection', 'column_name' => 'cpc_current.num_inventors', 'datatype' => 'int', 'sort' => 'y'),
    'cpc_num_patents' => array('entity_name'=>'cpc_subsection', 'column_name' => 'cpc_current.num_patents', 'datatype' => 'int', 'sort' => 'y'),
    'cpc_section_d' => array('entity_name'=>'cpc_subsection', 'column_name' => 'cpc_current.section_id', 'datatype' => 'string', 'sort' => 'y'),
    'cpc_subgroup_id' => array('entity_name'=>'cpc_subgroup', 'column_name' => 'cpc_current.subgroup_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subgroup_title' => array('entity_name'=>'cpc_subgroup', 'column_name' => 'cpc_current.subgroup_title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subsection_id' => array('entity_name'=>'cpc_subsection', 'column_name' => 'cpc_current.subsection_id', 'datatype' => 'string', 'sort' => 'y'),
    'cpc_subsection_title' => array('entity_name'=>'cpc_subsection', 'column_name' => 'cpc_current.subsection_title', 'datatype' => 'string', 'sort' => 'y'),
    'cpc_years_active' => array('entity_name'=>'cpc_subsection', 'column_name' => 'concat(year(cpc_current.first_seen_date),\'-\',year(cpc_current.last_seen_date))', 'datatype' => 'int', 'sort' => 'y'),
    'inventor_country' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.country', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_first_name' => array('entity_name'=>'inventor', 'column_name' => 'inventor.name_first', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_id' => array('entity_name'=>'inventor', 'column_name' => 'inventor.persistent_inventor_id', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_key_id' => array('entity_name'=>'inventor', 'column_name' => 'inventor.inventor_id', 'datatype' => 'int', 'sort' => 'n'),
    'inventor_last_name' => array('entity_name'=>'inventor', 'column_name' => 'inventor.name_last', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_lastknown_city' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_city', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_lastknown_country' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_country', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_lastknown_latitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_latitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_lastknown_longitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_longitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_lastknown_state' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_state', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_latitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.latitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_longitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.longitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_num_patents' => array('entity_name'=>'inventor', 'column_name' => 'inventor.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'inventor_state' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.state', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_years_active' => array('entity_name'=>'inventor', 'column_name' => 'concat(year(inventor.first_seen_date),\'-\',year(inventor.last_seen_date))', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_action_date' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.action_date', 'datatype' => 'date', 'sort' => 'n'),
    'ipc_class' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.ipc_class', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_classification_data_source' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.classification_data_source', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_classification_value' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.classification_value', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_main_group' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.main_group', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_num_assignees' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.num_assignees', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_num_inventors' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.num_inventors', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_section' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.section', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_subclass' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.subclass', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_subgroup' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.subgroup', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_symbol_position' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.symbol_position', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_version_indicator' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.ipc_version_indicator', 'datatype' => 'date', 'sort' => 'n'),
    'ipc_years_active' => array('entity_name'=>'ipc', 'column_name' => 'concat(year(ipcr.first_seen_date),\'-\',year(ipcr.last_seen_date))', 'datatype' => 'int', 'sort' => 'n'),
    'patent_abstract' => array('entity_name'=>'patent', 'column_name' => 'patent.abstract', 'datatype' => 'fulltext', 'sort' => 'n'),
    'patent_date' => array('entity_name'=>'patent', 'column_name' => 'patent.date', 'datatype' => 'date', 'sort' => 'n'),
    'patent_firstnamed_city' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_city', 'datatype' => 'string', 'sort' => 'n'),
    'patent_firstnamed_country' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_country', 'datatype' => 'string', 'sort' => 'n'),
    'patent_firstnamed_latitude' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_latitude', 'datatype' => 'float', 'sort' => 'n'),
    'patent_firstnamed_longitude' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_longitude', 'datatype' => 'float', 'sort' => 'n'),
    'patent_firstnamed_state' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_state', 'datatype' => 'string', 'sort' => 'n'),
    'patent_id' => array('entity_name'=>'patent', 'column_name' => 'patent.patent_id', 'datatype' => 'string', 'sort' => 'n'),
    'patent_kind' => array('entity_name'=>'patent', 'column_name' => 'patent.kind', 'datatype' => 'string', 'sort' => 'n'),
    'patent_num_citations' => array('entity_name'=>'patent', 'column_name' => 'patent.num_us_patents_cited', 'datatype' => 'int', 'sort' => 'n'),
    'patent_num_claims' => array('entity_name'=>'patent', 'column_name' => 'patent.num_claims', 'datatype' => 'int', 'sort' => 'n'),
    'patent_number' => array('entity_name'=>'patent', 'column_name' => 'patent.number', 'datatype' => 'string', 'sort' => 'n'),
    'patent_title' => array('entity_name'=>'patent', 'column_name' => 'patent.title', 'datatype' => 'fulltext', 'sort' => 'n'),
    'patent_type' => array('entity_name'=>'patent', 'column_name' => 'patent.type', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_mainclass_id' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.mainclass_id', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_mainclass_title' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.mainclass_title', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_num_assignees' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.num_assignees', 'datatype' => 'int', 'sort' => 'n'),
    'uspc_num_inventors' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.num_inventors', 'datatype' => 'int', 'sort' => 'n'),
    'uspc_num_patents' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'uspc_subclass_id' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.subclass_id', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_subclass_title' => array('entity_name'=>'uspc', 'column_name' => 'uspc_current.subclass_title', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_years_active' => array('entity_name'=>'uspc', 'column_name' => 'concat(year(uspc_current.first_seen_date),\'-\',year(uspc_current.last_seen_date))', 'datatype' => 'int', 'sort' => 'n')

);


$USPC_ENTITY_SPECS = array(
    array('entity_name'=>'uspc_mainclass', 'group_name'=>'uspc_mainclasses', 'keyId'=>'uspc_mainclass_id', 'join'=>'uspc_current'),
    array('entity_name'=>'uspc_subclass', 'group_name'=>'uspc_subclasses', 'keyId'=>'uspc_subclass_id', 'join'=>''),
    array('entity_name'=>'assignee', 'group_name'=>'assignees', 'keyId'=>'assignee_key_id', 'join'=>' left outer join patent_assignee on uspc_current.patent_id=patent_assignee.patent_id left outer JOIN assignee on patent_assignee.assignee_id=assignee.assignee_id left outer JOIN assignee_location on assignee.assignee_id=assignee_location.assignee_id'),
    array('entity_name'=>'patent', 'group_name'=>'patents', 'keyId'=>'patent_id', 'join'=>'left outer JOIN patent on uspc_current.patent_id=patent.patent_id'),
    array('entity_name'=>'inventor', 'group_name'=>'inventors', 'keyId'=>'inventor_key_id', 'join'=>'left outer join patent_inventor on uspc_current.patent_id=patent_inventor.patent_id left outer join inventor ON patent_inventor.inventor_id=inventor.inventor_id left outer JOIN inventor_location on inventor.inventor_id=inventor_location.inventor_id'),
    array('entity_name'=>'application', 'group_name'=>'applications', 'keyId'=>'app_id', 'join'=>'left outer join application on uspc_current.patent_id=application.patent_id'),
    array('entity_name'=>'ipc', 'group_name'=>'IPCs', 'keyId'=>'', 'join'=>'left outer join ipcr on uspc_current.patent_id=ipcr.patent_id'),
    array('entity_name'=>'cpc', 'group_name'=>'cpcs', 'keyId'=>'', 'join'=>'left outer join cpc_current on uspc_current.patent_id=cpc_current.patent_id')
);

$USPC_FIELD_SPECS = array
(
    'app_country' => array('entity_name'=>'application', 'column_name' => 'application.country', 'datatype' => 'string', 'sort' => 'n'),
    'app_date' => array('entity_name'=>'application', 'column_name' => 'application.date', 'datatype' => 'date', 'sort' => 'n'),
    'app_id' => array('entity_name'=>'application', 'column_name' => 'application.application_id', 'datatype' => 'string', 'sort' => 'n'),
    'app_number' => array('entity_name'=>'application', 'column_name' => 'application.number', 'datatype' => 'string', 'sort' => 'n'),
    'app_type' => array('entity_name'=>'application', 'column_name' => 'application.type', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_city' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.city', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_country' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.country', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_first_name' => array('entity_name'=>'assignee', 'column_name' => 'assignee.name_first', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_id' => array('entity_name'=>'assignee', 'column_name' => 'assignee.persistent_assignee_id', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_key_id' => array('entity_name'=>'assignee', 'column_name' => 'assignee.assignee_id', 'datatype' => 'int', 'sort' => 'n'),
    'assignee_lastknown_city' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_city', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_lastknown_country' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_country', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_lastknown_latitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_latitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_lastknown_longitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_longitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_lastknown_state' => array('entity_name'=>'assignee', 'column_name' => 'assignee.lastknown_state', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_last_name' => array('entity_name'=>'assignee', 'column_name' => 'assignee.name_last', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_latitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.latitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_longitude' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.longitude', 'datatype' => 'float', 'sort' => 'n'),
    'assignee_num_patents' => array('entity_name'=>'assignee', 'column_name' => 'assignee.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'assignee_organization' => array('entity_name'=>'assignee', 'column_name' => 'assignee.organization', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_state' => array('entity_name'=>'assignee', 'column_name' => 'assignee_location.state', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_type' => array('entity_name'=>'assignee', 'column_name' => 'assignee.type', 'datatype' => 'string', 'sort' => 'n'),
    'assignee_years_active' => array('entity_name'=>'assignee', 'column_name' => 'concat(year(assignee.first_seen_date),\'-\',year(assignee.last_seen_date))', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_city' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.city', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_group_id' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.group_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_group_title' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.group_title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_num_assignees' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.num_assignees', 'datatype' => 'int', 'sort' => 'n'),
    'cpc_num_inventors' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.num_inventors', 'datatype' => 'int', 'sort' => 'n'),
    'cpc_num_patents' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'cpc_section_d' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.section_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subgroup_id' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subgroup_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subgroup_title' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subgroup_title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subsection_id' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subsection_id', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_subsection_title' => array('entity_name'=>'cpc', 'column_name' => 'cpc_current.subsection_title', 'datatype' => 'string', 'sort' => 'n'),
    'cpc_years_active' => array('entity_name'=>'cpc', 'column_name' => 'concat(year(cpc_current.first_seen_date),\'-\',year(cpc_current.last_seen_date))', 'datatype' => 'int', 'sort' => 'n'),
    'inventor_country' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.country', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_first_name' => array('entity_name'=>'inventor', 'column_name' => 'inventor.name_first', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_id' => array('entity_name'=>'inventor', 'column_name' => 'inventor.persistent_inventor_id', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_key_id' => array('entity_name'=>'inventor', 'column_name' => 'inventor.inventor_id', 'datatype' => 'int', 'sort' => 'n'),
    'inventor_last_name' => array('entity_name'=>'inventor', 'column_name' => 'inventor.name_last', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_lastknown_city' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_city', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_lastknown_country' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_country', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_lastknown_latitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_latitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_lastknown_longitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_longitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_lastknown_state' => array('entity_name'=>'inventor', 'column_name' => 'inventor.lastknown_state', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_latitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.latitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_longitude' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.longitude', 'datatype' => 'float', 'sort' => 'n'),
    'inventor_num_patents' => array('entity_name'=>'inventor', 'column_name' => 'inventor.num_patents', 'datatype' => 'int', 'sort' => 'n'),
    'inventor_state' => array('entity_name'=>'inventor', 'column_name' => 'inventor_location.state', 'datatype' => 'string', 'sort' => 'n'),
    'inventor_years_active' => array('entity_name'=>'inventor', 'column_name' => 'concat(year(inventor.first_seen_date),\'-\',year(inventor.last_seen_date))', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_action_date' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.action_date', 'datatype' => 'date', 'sort' => 'n'),
    'ipc_class' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.ipc_class', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_classification_data_source' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.classification_data_source', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_classification_value' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.classification_value', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_main_group' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.main_group', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_num_assignees' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.num_assignees', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_num_inventors' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.num_inventors', 'datatype' => 'int', 'sort' => 'n'),
    'ipc_section' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.section', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_subclass' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.subclass', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_subgroup' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.subgroup', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_symbol_position' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.symbol_position', 'datatype' => 'string', 'sort' => 'n'),
    'ipc_version_indicator' => array('entity_name'=>'ipc', 'column_name' => 'ipcr.ipc_version_indicator', 'datatype' => 'date', 'sort' => 'n'),
    'ipc_years_active' => array('entity_name'=>'ipc', 'column_name' => 'concat(year(ipcr.first_seen_date),\'-\',year(ipcr.last_seen_date))', 'datatype' => 'int', 'sort' => 'n'),
    'patent_abstract' => array('entity_name'=>'patent', 'column_name' => 'patent.abstract', 'datatype' => 'fulltext', 'sort' => 'n'),
    'patent_date' => array('entity_name'=>'patent', 'column_name' => 'patent.date', 'datatype' => 'date', 'sort' => 'n'),
    'patent_firstnamed_city' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_city', 'datatype' => 'string', 'sort' => 'n'),
    'patent_firstnamed_country' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_country', 'datatype' => 'string', 'sort' => 'n'),
    'patent_firstnamed_latitude' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_latitude', 'datatype' => 'float', 'sort' => 'n'),
    'patent_firstnamed_longitude' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_longitude', 'datatype' => 'float', 'sort' => 'n'),
    'patent_firstnamed_state' => array('entity_name'=>'patent', 'column_name' => 'patent.firstnamed_state', 'datatype' => 'string', 'sort' => 'n'),
    'patent_id' => array('entity_name'=>'patent', 'column_name' => 'patent.patent_id', 'datatype' => 'string', 'sort' => 'n'),
    'patent_kind' => array('entity_name'=>'patent', 'column_name' => 'patent.kind', 'datatype' => 'string', 'sort' => 'n'),
    'patent_num_citations' => array('entity_name'=>'patent', 'column_name' => 'patent.num_us_patents_cited', 'datatype' => 'int', 'sort' => 'n'),
    'patent_num_claims' => array('entity_name'=>'patent', 'column_name' => 'patent.num_claims', 'datatype' => 'int', 'sort' => 'n'),
    'patent_number' => array('entity_name'=>'patent', 'column_name' => 'patent.number', 'datatype' => 'string', 'sort' => 'n'),
    'patent_title' => array('entity_name'=>'patent', 'column_name' => 'patent.title', 'datatype' => 'fulltext', 'sort' => 'n'),
    'patent_type' => array('entity_name'=>'patent', 'column_name' => 'patent.type', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_mainclass_id' => array('entity_name'=>'uspc_mainclass', 'column_name' => 'uspc_current.mainclass_id', 'datatype' => 'string', 'sort' => 'y'),
    'uspc_mainclass_title' => array('entity_name'=>'uspc_mainclass', 'column_name' => 'uspc_current.mainclass_title', 'datatype' => 'string', 'sort' => 'y'),
    'uspc_num_assignees' => array('entity_name'=>'uspc_mainclass', 'column_name' => 'uspc_current.num_assignees', 'datatype' => 'int', 'sort' => 'y'),
    'uspc_num_inventors' => array('entity_name'=>'uspc_mainclass', 'column_name' => 'uspc_current.num_inventors', 'datatype' => 'int', 'sort' => 'y'),
    'uspc_num_patents' => array('entity_name'=>'uspc_mainclass', 'column_name' => 'uspc_current.num_patents', 'datatype' => 'int', 'sort' => 'y'),
    'uspc_subclass_id' => array('entity_name'=>'uspc_subclass', 'column_name' => 'uspc_current.subclass_id', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_subclass_title' => array('entity_name'=>'uspc_subclass', 'column_name' => 'uspc_current.subclass_title', 'datatype' => 'string', 'sort' => 'n'),
    'uspc_years_active' => array('entity_name'=>'uspc_mainclass', 'column_name' => 'concat(year(uspc_current.first_seen_date),\'-\',year(uspc_current.last_seen_date))', 'datatype' => 'int', 'sort' => 'y')

);


