<?php

$ASSIGNEE_ENTITY_SPECS = array(
    array('entity_name' => 'assignee', 'group_name' => 'assignees', 'keyId' => 'assignee_key_id', 'distinctCountId' => 'assignee_key_id', 'default_fields' => array('assignee_id', 'assignee_first_name', 'assignee_last_name', 'assignee_organization'), 'join' => ' assignee left outer join patent_assignee on assignee.assignee_id=patent_assignee.assignee_id'),
    array('entity_name' => 'location', 'group_name' => 'locations', 'keyId' => 'location_key_id', 'distinctCountId' => 'location_key_id', 'join' => ' left outer JOIN location_assignee on assignee.assignee_id=location_assignee.assignee_id left outer join location as locationA on location_assignee.location_id=locationA.location_id'),
    array('entity_name' => 'patent', 'group_name' => 'patents', 'keyId' => 'patent_id', 'distinctCountId' => 'patent_id', 'join' => 'left outer JOIN patent on patent_assignee.patent_id=patent.patent_id'),
    array('entity_name' => 'inventor', 'group_name' => 'inventors', 'keyId' => 'inventor_key_id', 'distinctCountId' => 'inventor_key_id', 'join' => 'left outer join patent_inventor on patent_assignee.patent_id=patent_inventor.patent_id left outer join inventor ON patent_inventor.inventor_id=inventor.inventor_id left outer join location as locationI on patent_inventor.location_id=locationI.location_id left outer join assignee_inventor on assignee.assignee_id=assignee_inventor.assignee_id and inventor.inventor_id=assignee_inventor.inventor_id'),
    array('entity_name' => 'rawinventor', 'group_name' => 'rawinventors', 'keyId' => 'rawinventor_key_id', 'distinctCountId' => 'rawinventor_key_id', 'join' => 'left outer join inventor_rawinventor on inventor_rawinventor.patent_id = patent_assignee.patent_id'),
    array('entity_name' => 'application', 'group_name' => 'applications', 'keyId' => 'app_id', 'distinctCountId' => 'app_id', 'join' => 'left outer join application on patent_assignee.patent_id=application.patent_id'),
    array('entity_name' => 'ipc', 'group_name' => 'IPCs', 'keyId' => '', 'distinctCountId' => 'ipc_class', 'join' => 'left outer join ipcr on patent_assignee.patent_id=ipcr.patent_id'),
    array('entity_name' => 'uspc', 'group_name' => 'uspcs', 'keyId' => '', 'distinctCountId' => 'uspc_mainclass_id', 'join' => 'left outer join uspc_current_mainclass_copy on patent_assignee.patent_id=uspc_current_mainclass_copy.patent_id left outer join uspc_current_copy on uspc_current_mainclass_copy.patent_id=uspc_current_copy.patent_id and uspc_current_mainclass_copy.mainclass_id=uspc_current_copy.mainclass_id left outer join uspc_mainclass on uspc_current_mainclass_copy.mainclass_id=uspc_mainclass.id left outer join uspc_subclass on uspc_current_copy.subclass_id=uspc_subclass.id left outer join assignee_uspc_mainclass on assignee.assignee_id=assignee_uspc_mainclass.assignee_id and uspc_current_mainclass_copy.mainclass_id=assignee_uspc_mainclass.mainclass_id'),
    array('entity_name' => 'cpc', 'group_name' => 'cpcs', 'keyId' => '', 'distinctCountId' => 'cpc_group_id', 'join' => 'left outer join cpc_current_group_copy on patent_assignee.patent_id=cpc_current_group_copy.patent_id left outer join cpc_group on cpc_current_group_copy.group_id=cpc_group.id left outer join cpc_current_copy on cpc_current_group_copy.patent_id=cpc_current_copy.patent_id and cpc_group.id=cpc_current_copy.group_id  left outer join cpc_subsection on cpc_current_copy.subsection_id=cpc_subsection.id left outer join cpc_subgroup on cpc_current_copy.subgroup_id=cpc_subgroup.id left outer join assignee_cpc_group on assignee.assignee_id=assignee_cpc_group.assignee_id and cpc_current_group_copy.group_id=assignee_cpc_group.group_id'),
    array('entity_name' => 'nber', 'group_name' => 'nbers', 'keyId' => '', 'distinctCountId' => 'nber_subcategory_id', 'join' => 'left outer join nber_copy on patent_assignee.patent_id=nber_copy.patent_id left outer join nber_category on nber_copy.category_id=nber_category.id left outer join nber_subcategory on nber_copy.subcategory_id=nber_subcategory.id left outer join assignee_nber_subcategory on assignee.assignee_id=assignee_nber_subcategory.assignee_id and nber_copy.subcategory_id=assignee_nber_subcategory.subcategory_id'),
    array('entity_name' => 'year', 'group_name' => 'years', 'keyId' => '', 'distinctCountId' => 'year_id', 'join' => 'left outer JOIN patent as patent_year on patent_assignee.patent_id=patent_year.patent_id left outer join assignee_year on assignee.assignee_id=assignee_year.assignee_id and patent_year.year=assignee_year.patent_year'),
    array('entity_name' => 'wipo', 'group_name' => 'wipos', 'keyId' => '', 'distinctCountId' => 'wipo_field_id', 'join' => 'left outer join wipo on patent_assignee.patent_id=wipo.patent_id left outer join wipo_field on wipo.field_id=wipo_field.id'),
    array('entity_name' => 'government_interest', 'group_name' => 'gov_interests', 'keyId' => '', 'distinctCountId' => 'govint_patent_id', 'join' => 'left outer join government_interest on patent_assignee.patent_id=government_interest.patent_id left outer join patent_govintorg on patent_assignee.patent_id=patent_govintorg.patent_id left outer join patent_contractawardnumber on patent_assignee.patent_id=patent_contractawardnumber.patent_id left outer join government_organization on patent_govintorg.organization_id=government_organization.organization_id'),
    array('entity_name' => 'lawyer', 'group_name' => 'lawyers', 'keyId' => '', 'distinctCountId' => 'lawyer_id', 'join' => 'left outer join patent_lawyer ON patent_assignee.patent_id=patent_lawyer.patent_id left outer join lawyer on lawyer.lawyer_id=patent_lawyer.lawyer_id'),
    array('entity_name' => 'examiner', 'group_name' => 'examiners', 'keyId' => '', 'distinctCountId' => 'examiner_id', 'join' => 'left outer join patent_examiner on patent_examiner.patent_id=patent_assignee.patent_id left outer join examiner on examiner.examiner_id=patent_examiner.examiner_id'),
    array('entity_name' => 'foreign_prior', 'group_name' => 'foreign_priority', 'keyId' => '', 'distinctCountId' => 'foreign_doc_number', 'join' => 'left outer join foreignpriority on foreignpriority.patent_id=patent_assignee.patent_id'),
    array('entity_name' => 'pct_dat', 'group_name' => 'pct_data', 'keyId' => '', 'distinctCountId' => 'pct_id', 'join' => 'left outer join pctdata on pctdata.patent_id=patent_assignee.patent_id')


);

$ASSIGNEE_FIELD_SPECS = array
(
    'location_county' => array('entity_name' => 'location', 'column_name' => 'locationA.county', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'location_county_fips' => array('entity_name' => 'location', 'column_name' => 'locationA.county_fips', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'location_state_fips' => array('entity_name' => 'location', 'column_name' => 'locationA.state_fips', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'examiner_first_name' => array('entity_name' => 'examiner', 'column_name' => 'examiner.name_first', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'examiner_id' => array('entity_name' => 'examiner', 'column_name' => 'examiner.persistent_examiner_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'examiner_key_id' => array('entity_name' => 'examiner', 'column_name' => 'examiner.examiner_id', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'examiner_last_name' => array('entity_name' => 'examiner', 'column_name' => 'examiner.name_last', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'examiner_role' => array('entity_name' => 'examiner', 'column_name' => 'patent_examiner.role', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'examiner_group' => array('entity_name' => 'examiner', 'column_name' => 'examiner.group', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'forprior_country' => array('entity_name' => 'foreign_prior', 'column_name' => 'foreignpriority.country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'forprior_date' => array('entity_name' => 'foreign_prior', 'column_name' => 'foreignpriority.date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'forprior_kind' => array('entity_name' => 'foreign_prior', 'column_name' => 'foreignpriority.kind', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'forprior_docnumber' => array('entity_name' => 'foreign_prior', 'column_name' => 'foreignpriority.foreign_doc_number', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'forprior_sequence' => array('entity_name' => 'foreign_prior', 'column_name' => 'foreignpriority.sequence', 'datatype' => 'int', 'query' => 'n', 'sort' => 'suppl'),
    'inventor_county' => array('entity_name' => 'inventor', 'column_name' => 'locationI.county', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_county_fips' => array('entity_name' => 'inventor', 'column_name' => 'locationI.county_fips', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_state_fips' => array('entity_name' => 'inventor', 'column_name' => 'locationI.state_fips', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'lawyer_first_name' => array('entity_name' => 'lawyer', 'column_name' => 'lawyer.name_first', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'lawyer_first_seen_date' => array('entity_name' => 'lawyer', 'column_name' => 'lawyer.first_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'lawyer_id' => array('entity_name' => 'lawyer', 'column_name' => 'lawyer.persistent_lawyer_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'lawyer_key_id' => array('entity_name' => 'lawyer', 'column_name' => 'lawyer.lawyer_id', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'lawyer_last_name' => array('entity_name' => 'lawyer', 'column_name' => 'lawyer.name_last', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'lawyer_last_seen_date' => array('entity_name' => 'lawyer', 'column_name' => 'lawyer.last_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'lawyer_organization' => array('entity_name' => 'lawyer', 'column_name' => 'lawyer.organization', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'lawyer_sequence' => array('entity_name' => 'lawyer', 'column_name' => 'patent_lawyer.sequence', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'lawyer_total_num_patents' => array('entity_name' => 'lawyer', 'column_name' => 'lawyer.num_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'lawyer_total_num_assignees' => array('entity_name' => 'lawyer', 'column_name' => 'lawyer.num_assignees', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'lawyer_total_num_inventors' => array('entity_name' => 'lawyer', 'column_name' => 'lawyer.num_inventors', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'pct_doctype' => array('entity_name' => 'pct_dat', 'column_name' => 'pctdata.doc_type', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'pct_date' => array('entity_name' => 'pct_dat', 'column_name' => 'pctdata.date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'pct_102_date' => array('entity_name' => 'pct_dat', 'column_name' => 'pctdata.102_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'pct_371_date' => array('entity_name' => 'pct_dat', 'column_name' => 'pctdata.371_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'pct_kind' => array('entity_name' => 'pct_dat', 'column_name' => 'pctdata.kind', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'pct_docnumber' => array('entity_name' => 'pct_dat', 'column_name' => 'pctdata.doc_number', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'detail_desc_length' => array('entity_name' => 'patent', 'column_name' => 'patent.detail_desc_length', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),

    'app_country' => array('entity_name' => 'application', 'column_name' => 'application.country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'app_date' => array('entity_name' => 'application', 'column_name' => 'application.date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'app_id' => array('entity_name' => 'application', 'column_name' => 'application.application_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'app_number' => array('entity_name' => 'application', 'column_name' => 'application.number', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'app_type' => array('entity_name' => 'application', 'column_name' => 'application.type', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_first_name' => array('entity_name' => 'assignee', 'column_name' => 'assignee.name_first', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'assignee_first_seen_date' => array('entity_name' => 'assignee', 'column_name' => 'assignee.first_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'y'),
    'assignee_id' => array('entity_name' => 'assignee', 'column_name' => 'assignee.persistent_assignee_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'assignee_key_id' => array('entity_name' => 'assignee', 'column_name' => 'assignee.assignee_id', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'assignee_lastknown_city' => array('entity_name' => 'assignee', 'column_name' => 'assignee.lastknown_city', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'assignee_lastknown_country' => array('entity_name' => 'assignee', 'column_name' => 'assignee.lastknown_country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'assignee_lastknown_latitude' => array('entity_name' => 'assignee', 'column_name' => 'assignee.lastknown_latitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'y'),
    'assignee_lastknown_location_id' => array('entity_name' => 'assignee', 'column_name' => 'assignee.lastknown_persistent_location_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'assignee_lastknown_longitude' => array('entity_name' => 'assignee', 'column_name' => 'assignee.lastknown_longitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'y'),
    'assignee_lastknown_state' => array('entity_name' => 'assignee', 'column_name' => 'assignee.lastknown_state', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'assignee_last_name' => array('entity_name' => 'assignee', 'column_name' => 'assignee.name_last', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'assignee_last_seen_date' => array('entity_name' => 'assignee', 'column_name' => 'assignee.last_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'y'),
    'assignee_organization' => array('entity_name' => 'assignee', 'column_name' => 'assignee.organization', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'assignee_total_num_patents' => array('entity_name' => 'assignee', 'column_name' => 'assignee.num_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'assignee_total_num_inventors' => array('entity_name' => 'assignee', 'column_name' => 'assignee.num_inventors', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_type' => array('entity_name' => 'assignee', 'column_name' => 'assignee.type', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'cpc_category' => array('entity_name' => 'cpc', 'column_name' => 'cpc_current_copy.category', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_first_seen_date' => array('entity_name' => 'cpc', 'column_name' => 'cpc_group.first_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_group_id' => array('entity_name' => 'cpc', 'column_name' => 'cpc_group.id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_group_title' => array('entity_name' => 'cpc', 'column_name' => 'cpc_group.title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_last_seen_date' => array('entity_name' => 'cpc', 'column_name' => 'cpc_group.last_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_section_id' => array('entity_name' => 'cpc', 'column_name' => 'cpc_current_group_copy.section_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_sequence' => array('entity_name' => 'cpc', 'column_name' => 'cpc_current_copy.sequence', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),

    'cpc_subgroup_id' => array('entity_name' => 'cpc', 'column_name' => 'cpc_current_copy.subgroup_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_subgroup_title' => array('entity_name' => 'cpc', 'column_name' => 'cpc_subgroup.title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_subsection_id' => array('entity_name' => 'cpc', 'column_name' => 'cpc_current_copy.subsection_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_subsection_title' => array('entity_name' => 'cpc', 'column_name' => 'cpc_subsection.title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_total_num_assignees' => array('entity_name' => 'cpc', 'column_name' => 'cpc_group.num_assignees', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_total_num_inventors' => array('entity_name' => 'cpc', 'column_name' => 'cpc_group.num_inventors', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_total_num_patents' => array('entity_name' => 'cpc', 'column_name' => 'cpc_group.num_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_num_patents_for_assignee' => array('entity_name' => 'cpc', 'column_name' => 'assignee_cpc_group.num_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'govint_raw_statement' => array('entity_name' => 'government_interest', 'column_name' => 'government_interest.gi_statement', 'datatype' => 'fulltext', 'query' => 'y', 'sort' => 'suppl'),
    'govint_org_id' => array('entity_name' => 'government_interest', 'column_name' => 'patent_govintorg.organization_id', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'govint_org_name' => array('entity_name' => 'government_interest', 'column_name' => 'government_organization.name', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'govint_org_level_one' => array('entity_name' => 'government_interest', 'column_name' => 'government_organization.level_one', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'govint_org_level_two' => array('entity_name' => 'government_interest', 'column_name' => 'government_organization.level_two', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'govint_org_level_three' => array('entity_name' => 'government_interest', 'column_name' => 'government_organization.level_three', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'govint_contract_award_number' => array('entity_name' => 'government_interest', 'column_name' => 'patent_contractawardnumber.contract_award_number', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_city' => array('entity_name' => 'inventor', 'column_name' => 'locationI.city', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_country' => array('entity_name' => 'inventor', 'column_name' => 'locationI.country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_first_name' => array('entity_name' => 'inventor', 'column_name' => 'inventor.name_first', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_first_seen_date' => array('entity_name' => 'inventor', 'column_name' => 'inventor.first_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_id' => array('entity_name' => 'inventor', 'column_name' => 'inventor.persistent_inventor_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_key_id' => array('entity_name' => 'inventor', 'column_name' => 'inventor.inventor_id', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_last_name' => array('entity_name' => 'inventor', 'column_name' => 'inventor.name_last', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_lastknown_city' => array('entity_name' => 'inventor', 'column_name' => 'inventor.lastknown_city', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_lastknown_country' => array('entity_name' => 'inventor', 'column_name' => 'inventor.lastknown_country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_lastknown_latitude' => array('entity_name' => 'inventor', 'column_name' => 'inventor.lastknown_latitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'inventor_lastknown_location_id' => array('entity_name' => 'inventor', 'column_name' => 'inventor.lastknown_persistent_location_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_lastknown_longitude' => array('entity_name' => 'inventor', 'column_name' => 'inventor.lastknown_longitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'inventor_lastknown_state' => array('entity_name' => 'inventor', 'column_name' => 'inventor.lastknown_state', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_last_seen_date' => array('entity_name' => 'inventor', 'column_name' => 'inventor.last_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_latitude' => array('entity_name' => 'inventor', 'column_name' => 'locationI.latitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'inventor_location_id' => array('entity_name' => 'inventor', 'column_name' => 'locationI.persistent_location_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_longitude' => array('entity_name' => 'inventor', 'column_name' => 'locationI.longitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'inventor_num_patents_for_assignee' => array('entity_name' => 'inventor', 'column_name' => 'assignee_inventor.num_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_state' => array('entity_name' => 'inventor', 'column_name' => 'locationI.state', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_total_num_patents' => array('entity_name' => 'inventor', 'column_name' => 'inventor.num_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_total_num_assignees' => array('entity_name' => 'inventor', 'column_name' => 'inventor.num_assignees', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_action_date' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.action_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_class' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.ipc_class', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_classification_data_source' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.classification_data_source', 'datatype' => 'string', 'query' => 'n', 'sort' => 'suppl'),
    'ipc_classification_value' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.classification_value', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_first_seen_date' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.first_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_last_seen_date' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.last_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_main_group' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.main_group', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_section' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.section', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_sequence' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.sequence', 'datatype' => 'int', 'query' => 'n', 'sort' => 'suppl'),
    'ipc_subclass' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.subclass', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_subgroup' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.subgroup', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_symbol_position' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.symbol_position', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_total_num_assignees' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.num_assignees', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_total_num_inventors' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.num_inventors', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_version_indicator' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.ipc_version_indicator', 'datatype' => 'date', 'query' => 'n', 'sort' => 'suppl'),
    'location_city' => array('entity_name' => 'location', 'column_name' => 'locationA.city', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'location_country' => array('entity_name' => 'location', 'column_name' => 'locationA.country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'location_id' => array('entity_name' => 'location', 'column_name' => 'locationA.persistent_location_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'location_latitude' => array('entity_name' => 'location', 'column_name' => 'locationA.latitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'location_key_id' => array('entity_name' => 'location', 'column_name' => 'locationA.location_id', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'location_longitude' => array('entity_name' => 'location', 'column_name' => 'locationA.longitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'location_state' => array('entity_name' => 'location', 'column_name' => 'locationA.state', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'nber_category_id' => array('entity_name' => 'nber', 'column_name' => 'nber_copy.category_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'nber_category_title' => array('entity_name' => 'nber', 'column_name' => 'nber_category.title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'nber_first_seen_date' => array('entity_name' => 'nber', 'column_name' => 'nber_subcategory.first_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'y'),
    'nber_last_seen_date' => array('entity_name' => 'nber', 'column_name' => 'nber_subcategory.last_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'y'),
    'nber_subcategory_id' => array('entity_name' => 'nber', 'column_name' => 'nber_copy.subcategory_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'nber_subcategory_title' => array('entity_name' => 'nber', 'column_name' => 'nber_subcategory.title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'nber_total_num_assignees' => array('entity_name' => 'nber', 'column_name' => 'nber_subcategory.num_assignees', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'nber_total_num_inventors' => array('entity_name' => 'nber', 'column_name' => 'nber_subcategory.num_inventors', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'nber_total_num_patents' => array('entity_name' => 'nber', 'column_name' => 'nber_subcategory.num_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),

    'nber_num_patents_for_assignee' => array('entity_name' => 'nber', 'column_name' => 'assignee_nber_subcategory.num_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'patent_abstract' => array('entity_name' => 'patent', 'column_name' => 'patent.abstract', 'datatype' => 'fulltext', 'query' => 'y', 'sort' => 'suppl'),
    'patent_date' => array('entity_name' => 'patent', 'column_name' => 'patent.date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'patent_firstnamed_assignee_id' => array('entity_name' => 'patent', 'column_name' => 'patent.firstnamed_assignee_persistent_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'patent_firstnamed_assignee_city' => array('entity_name' => 'patent', 'column_name' => 'patent.firstnamed_assignee_city', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'patent_firstnamed_assignee_country' => array('entity_name' => 'patent', 'column_name' => 'patent.firstnamed_assignee_country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'patent_firstnamed_assignee_latitude' => array('entity_name' => 'patent', 'column_name' => 'patent.firstnamed_assignee_latitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'patent_firstnamed_assignee_location_id' => array('entity_name' => 'patent', 'column_name' => 'patent.firstnamed_assignee_persistent_location_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'patent_firstnamed_assignee_longitude' => array('entity_name' => 'patent', 'column_name' => 'patent.firstnamed_assignee_longitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'patent_firstnamed_assignee_state' => array('entity_name' => 'patent', 'column_name' => 'patent.firstnamed_assignee_state', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'patent_firstnamed_inventor_id' => array('entity_name' => 'patent', 'column_name' => 'patent.firstnamed_inventor_persistent_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'patent_firstnamed_inventor_city' => array('entity_name' => 'patent', 'column_name' => 'patent.firstnamed_inventor_city', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'patent_firstnamed_inventor_country' => array('entity_name' => 'patent', 'column_name' => 'patent.firstnamed_inventor_country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'patent_firstnamed_inventor_latitude' => array('entity_name' => 'patent', 'column_name' => 'patent.firstnamed_inventor_latitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'patent_firstnamed_inventor_location_id' => array('entity_name' => 'patent', 'column_name' => 'patent.firstnamed_inventor_persistent_location_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'patent_firstnamed_inventor_longitude' => array('entity_name' => 'patent', 'column_name' => 'patent.firstnamed_inventor_longitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'patent_firstnamed_inventor_state' => array('entity_name' => 'patent', 'column_name' => 'patent.firstnamed_inventor_state', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'patent_id' => array('entity_name' => 'patent', 'column_name' => 'patent.patent_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'patent_kind' => array('entity_name' => 'patent', 'column_name' => 'patent.kind', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'patent_num_cited_by_us_patents' => array('entity_name' => 'patent', 'column_name' => 'patent.num_times_cited_by_us_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'patent_num_combined_citations' => array('entity_name' => 'patent', 'column_name' => 'patent.num_total_documents_cited', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'patent_num_foreign_citations' => array('entity_name' => 'patent', 'column_name' => 'patent.num_foreign_documents_cited', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'patent_num_us_application_citations' => array('entity_name' => 'patent', 'column_name' => 'patent.num_us_applications_cited', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'patent_num_us_patent_citations' => array('entity_name' => 'patent', 'column_name' => 'patent.num_us_patents_cited', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'patent_num_claims' => array('entity_name' => 'patent', 'column_name' => 'patent.num_claims', 'datatype' => 'int', 'query' => 'n', 'sort' => 'suppl'),
    'patent_number' => array('entity_name' => 'patent', 'column_name' => 'patent.number', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'patent_title' => array('entity_name' => 'patent', 'column_name' => 'patent.title', 'datatype' => 'fulltext', 'query' => 'y', 'sort' => 'suppl'),
    'patent_type' => array('entity_name' => 'patent', 'column_name' => 'patent.type', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'rawinventor_first_name' => array('entity_name' => 'rawinventor', 'column_name' => 'inventor_rawinventor.name_first', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'rawinventor_last_name' => array('entity_name' => 'rawinventor', 'column_name' => 'inventor_rawinventor.name_last', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),

    'uspc_first_seen_date' => array('entity_name' => 'uspc', 'column_name' => 'uspc_mainclass.first_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_last_seen_date' => array('entity_name' => 'uspc', 'column_name' => 'uspc_mainclass.last_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_mainclass_id' => array('entity_name' => 'uspc', 'column_name' => 'uspc_mainclass.id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_mainclass_title' => array('entity_name' => 'uspc', 'column_name' => 'uspc_mainclass.title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_sequence' => array('entity_name' => 'uspc', 'column_name' => 'uspc_current_copy.sequence', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_subclass_id' => array('entity_name' => 'uspc', 'column_name' => 'uspc_current_copy.subclass_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_subclass_title' => array('entity_name' => 'uspc', 'column_name' => 'uspc_subclass.title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_total_num_assignees' => array('entity_name' => 'uspc', 'column_name' => 'uspc_mainclass.num_assignees', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_total_num_inventors' => array('entity_name' => 'uspc', 'column_name' => 'uspc_mainclass.num_inventors', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_total_num_patents' => array('entity_name' => 'uspc', 'column_name' => 'uspc_mainclass.num_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_num_patents_for_assignee' => array('entity_name' => 'uspc', 'column_name' => 'assignee_uspc_mainclass.num_patents', 'datatype' => 'int', 'query' => 'n', 'sort' => 'suppl'),
    'year_id' => array('entity_name' => 'year', 'column_name' => 'patent_year.year', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'year_num_patents_for_assignee' => array('entity_name' => 'year', 'column_name' => 'assignee_year.num_patents', 'datatype' => 'int', 'query' => 'n', 'sort' => 'suppl'),
    'wipo_field_id' => array('entity_name' => 'wipo', 'column_name' => 'wipo.field_id', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'wipo_field_title' => array('entity_name' => 'wipo', 'column_name' => 'wipo_field.field_title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'wipo_sector_title' => array('entity_name' => 'wipo', 'column_name' => 'wipo_field.sector_title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'wipo_sequence' => array('entity_name' => 'wipo', 'column_name' => 'wipo.sequence', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl')

);


/*
 * FIELD_SPECS:     defines the fields available for an entity, in what table/column it can be found, and other
 *                  attributes of the field/column.
 * key:             the unique internal and external name for the field
 * entity_name:     the name of the parent entity; must match an 'entity_name' in the ENTITY_SPECS
 * column_name:     the SQL field expression to obtain the data; could be a table.column or a more complex expression,
 *                  as long as it results in a single value.
 * datatype:        One of 'string', 'int', 'float', 'date', 'fulltext'
 * sort:            'y' or 'n' depending on if the primary entity can be sorted on this field. Only set to 'y' when
 *                  the field would be unique for that primary entity. If the field is part of a one-to-many, then
 *                  it must be 'n'; otherwise the return results would likely get mixed up.
 */




 $fp = fopen('specs/assignee-entity-specs.json', 'w');
                fwrite($fp, json_encode($ASSIGNEE_ENTITY_SPECS));
                fclose($fp);

 $fp = fopen('specs/assignee-field-specs.json', 'w');
                fwrite($fp, json_encode($ASSIGNEE_FIELD_SPECS));
                fclose($fp);

 ?>