<?php


$PATENT_ENTITY_SPECS=array(
    array('entity_name'=>'patent', 'group_name'=>'patents', 'keyId'=>'patent_id', 'distinctCountId'=>'patent_id','default_fields'=>array('patent_id','patent_number','patent_title'), 'solr_collection'=>'schema_collection'),
    array('entity_name'=>'inventor', 'group_name'=>'inventors', 'keyId'=>'inventor_key_id', 'distinctCountId'=>'inventor_key_id','solr_collection'=>'schema_collection'),
    array('entity_name'=>'rawinventor', 'group_name'=>'rawinventors', 'keyId'=>'rawinventor_key_id', 'distinctCountId'=>'rawinventor_key_id','solr_collection'=>'schema_collection'),
    array('entity_name'=>'assignee', 'group_name'=>'assignees', 'keyId'=>'assignee_key_id', 'distinctCountId'=>'assignee_key_id','solr_collection'=>'schema_collection'),
    array('entity_name'=>'application', 'group_name'=>'applications', 'keyId'=>'app_id', 'distinctCountId'=>'app_id','solr_collection'=>'schema_collection'),
    array('entity_name'=>'ipc', 'group_name'=>'IPCs', 'keyId'=>'', 'distinctCountId'=>'ipc_class','solr_collection'=>'schema_collection'),
    array('entity_name'=>'applicationcitation', 'group_name'=>'application_citations', 'keyId'=>'', 'distinctCountId'=>'appcit_app_number','solr_collection'=>'schema_collection'),
    array('entity_name'=>'cited_patent', 'group_name'=>'cited_patents', 'keyId'=>'', 'distinctCountId'=>'cited_patent_id','solr_collection'=>'schema_collection'),
    array('entity_name'=>'citedby_patent', 'group_name'=>'citedby_patents', 'keyId'=>'', 'distinctCountId'=>'citedby_patent_id','solr_collection'=>'schema_collection'),
    array('entity_name'=>'uspc', 'group_name'=>'uspcs', 'keyId'=>'', 'distinctCountId'=>'uspc_mainclass_id','solr_collection'=>'schema_collection'),
    array('entity_name'=>'cpc', 'group_name'=>'cpcs', 'keyId'=>'', 'distinctCountId'=>'cpc_subsection_id','solr_collection'=>'schema_collection'),
    array('entity_name'=>'nber', 'group_name'=>'nbers', 'keyId'=>'', 'distinctCountId'=>'nber_subcategory_id','solr_collection'=>'schema_collection'),
    array('entity_name'=>'wipo', 'group_name'=>'wipos', 'keyId'=>'', 'distinctCountId'=>'wipo_field_id','solr_collection'=>'schema_collection'),
    array('entity_name'=>'government_interest', 'group_name'=>'gov_interests', 'keyId'=>'', 'distinctCountId'=>'govint_patent_id','solr_collection'=>'schema_collection')


);

/*
 * FIELD_SPECS:     defines the fields available for an entity, in what table/column it can be found, and other
 *                  attributes of the field/column.
 * key:             the unique internal and external name for the field
 * entity_name:     the name of the parent entity; must match an 'entity_name' in the ENTITY_SPECS
 * column_name:     the SQL field expression to obtain the data; could be a table.column or a more complex expression,
 *                  as long as it results in a single value.
 * datatype:        One of 'string', 'int', 'float', 'date', 'fulltext'
 * sort:            'y' or 'n' depending on if the primary entity can be sorted on this field. Only set to 'y' when
 *                  the field would be unique for that primary entity. If the field is part of a one-to-many, then
 *                  it must be 'n'; otherwise the return results would likely get mixed up.
 */

$PATENT_FIELD_SPECS=array
(
    'app_country' => array('entity_name'=>'application', 'column_name' => 'applications.app_country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'app_date' => array('entity_name'=>'application', 'column_name' => 'applications.app_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'y'),
    'app_id' => array('entity_name'=>'application', 'column_name' => 'applications.app_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'app_number' => array('entity_name'=>'application', 'column_name' => 'applications.app_number', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'app_type' => array('entity_name'=>'application', 'column_name' => 'applications.app_type', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'appcit_app_number' => array('entity_name'=>'applicationcitation', 'column_name' => 'application_citations.appcit_app_number', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'appcit_category' => array('entity_name'=>'applicationcitation', 'column_name' => 'application_citations.appcit_category', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'appcit_date' => array('entity_name'=>'applicationcitation', 'column_name' => 'application_citations.appcit_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'appcit_kind' => array('entity_name'=>'applicationcitation', 'column_name' => 'application_citations.appcit_kind', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'appcit_name' => array('entity_name'=>'applicationcitation', 'column_name' => 'application_citations.appcit_name', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'appcit_sequence' => array('entity_name'=>'applicationcitation', 'column_name' => 'application_citations.appcit_sequence', 'datatype' => 'int', 'query' => 'n', 'sort' => 'suppl'),
    'assignee_city' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_city', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_country' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_first_name' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_first_name', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_first_seen_date' => array('entity_name' => 'assignee', 'column_name' => 'assignee.first_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_id' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_key_id' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_key_id', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_lastknown_city' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_lastknown_city', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_lastknown_country' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_lastknown_country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_lastknown_latitude' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_lastknown_latitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'assignee_lastknown_location_id' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_lastknown_location_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_lastknown_longitude' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_lastknown_longitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'assignee_lastknown_state' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_lastknown_state', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_last_name' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_last_name', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_last_seen_date' => array('entity_name' => 'assignee', 'column_name' => 'assignee.last_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_latitude' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_latitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'assignee_location_id' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_location_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_longitude' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_longitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'assignee_organization' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_organization', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_sequence' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_sequence', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_state' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_state', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_total_num_patents' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_total_num_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_total_num_inventors' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_total_num_inventors', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'assignee_type' => array('entity_name'=>'assignee', 'column_name' => 'assignees.assignee_type', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'citedby_patent_category' => array('entity_name'=>'citedby_patent', 'column_name' => 'citedby_patents.citedby_patent_category', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'citedby_patent_date' => array('entity_name'=>'citedby_patent', 'column_name' => 'citedby_patents.citedby_patent_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'citedby_patent_id' => array('entity_name'=>'citedby_patent', 'column_name' => 'citedby_patents.citedby_patent_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'citedby_patent_kind' => array('entity_name'=>'citedby_patent', 'column_name' => 'citedby_patents.citedby_patent_kind', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'citedby_patent_number' => array('entity_name'=>'citedby_patent', 'column_name' => 'citedby_patents.citedby_patent_number', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'citedby_patent_title' => array('entity_name'=>'citedby_patent', 'column_name' => 'citedby_patents.citedby_patent_title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cited_patent_category' => array('entity_name'=>'cited_patent', 'column_name' => 'cited_patents.cited_patent_category', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cited_patent_date' => array('entity_name'=>'cited_patent', 'column_name' => 'cited_patents.cited_patent_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'cited_patent_id' => array('entity_name'=>'cited_patent', 'column_name' => 'cited_patents.cited_patent_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cited_patent_kind' => array('entity_name'=>'cited_patent', 'column_name' => 'cited_patents.cited_patent_kind', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cited_patent_number' => array('entity_name'=>'cited_patent', 'column_name' => 'cited_patents.cited_patent_number', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cited_patent_sequence' => array('entity_name'=>'cited_patent', 'column_name' => 'cited_patents.cited_patent_sequence', 'datatype' => 'int', 'query' => 'n', 'sort' => 'suppl'),
    'cited_patent_title' => array('entity_name'=>'cited_patent', 'column_name' => 'cited_patents.cited_patent_title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_category' => array('entity_name'=>'cpc', 'column_name' => 'cpcs.cpc_category', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_first_seen_date' => array('entity_name' => 'cpc', 'column_name' => 'cpc_subsection.first_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_group_id' => array('entity_name'=>'cpc', 'column_name' => 'cpcs.cpc_group_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_group_title' => array('entity_name'=>'cpc', 'column_name' => 'cpcs.cpc_group_title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_last_seen_date' => array('entity_name' => 'cpc', 'column_name' => 'cpc_subsection.last_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_section_id' => array('entity_name'=>'cpc', 'column_name' => 'cpcs.cpc_section_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_sequence' => array('entity_name'=>'cpc', 'column_name' => 'cpcs.cpc_sequence', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_subgroup_id' => array('entity_name'=>'cpc', 'column_name' => 'cpcs.cpc_subgroup_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_subgroup_title' => array('entity_name'=>'cpc', 'column_name' => 'cpcs.cpc_subgroup_title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_subsection_id' => array('entity_name'=>'cpc', 'column_name' => 'cpcs.cpc_subsection_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_subsection_title' => array('entity_name'=>'cpc', 'column_name' => 'cpcs.cpc_subsection_title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_total_num_inventors' => array('entity_name'=>'cpc', 'column_name' => 'cpcs.cpc_total_num_inventors', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_total_num_patents' => array('entity_name'=>'cpc', 'column_name' => 'cpcs.cpc_total_num_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'cpc_total_num_assignees' => array('entity_name'=>'cpc', 'column_name' => 'cpcs.cpc_total_num_assignees', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'govint_raw_statement' => array('entity_name'=>'government_interest', 'column_name' => 'government_interests.govint_raw_statement', 'datatype' => 'fulltext', 'query' => 'y', 'sort' => 'suppl'),
    'govint_org_id' => array('entity_name'=>'government_interest', 'column_name' => 'government_interests.govint_org_id', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'govint_org_name' => array('entity_name'=>'government_interest', 'column_name' => 'government_interests.govint_org_name', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'govint_org_level_one' => array('entity_name'=>'government_interest', 'column_name' => 'government_interests.govint_org_level_one', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'govint_org_level_two' => array('entity_name'=>'government_interest', 'column_name' => 'government_interests.govint_org_level_two', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'govint_org_level_three' => array('entity_name'=>'government_interest', 'column_name' => 'government_interests.govint_org_level_three', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'govint_contract_award_number' => array('entity_name'=>'government_interest', 'column_name' => 'government_interests.govint_contract_award_number', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_city' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_city', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_country' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_first_name' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_first_name', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_first_seen_date' => array('entity_name' => 'inventor', 'column_name' => 'inventor.first_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_id' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_key_id' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_key_id', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_last_name' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_last_name', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_lastknown_city' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_lastknown_city', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_lastknown_country' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_lastknown_country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_lastknown_latitude' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_lastknown_latitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'inventor_lastknown_location_id' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_lastknown_location_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_lastknown_longitude' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_lastknown_longitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'inventor_lastknown_state' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_lastknown_state', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_last_seen_date' => array('entity_name' => 'inventor', 'column_name' => 'inventor.last_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_latitude' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_latitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'inventor_location_id' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_location_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_longitude' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_longitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'suppl'),
    'inventor_sequence' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_sequence', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_state' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_state', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_total_num_patents' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_total_num_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'inventor_total_num_assignees' => array('entity_name'=>'inventor', 'column_name' => 'inventors.inventor_total_num_assignees', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_action_date' => array('entity_name'=>'ipc', 'column_name' => 'ipcs.ipc_action_date', 'datatype' => 'date', 'query' => 'n', 'sort' => 'suppl'),
    'ipc_class' => array('entity_name'=>'ipc', 'column_name' => 'ipcs.ipc_class', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_classification_data_source' => array('entity_name'=>'ipc', 'column_name' => 'ipcs.ipc_classification_data_source', 'datatype' => 'string', 'query' => 'n', 'sort' => 'suppl'),
    'ipc_classification_value' => array('entity_name'=>'ipc', 'column_name' => 'ipcs.ipc_classification_value', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_first_seen_date' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.first_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_last_seen_date' => array('entity_name' => 'ipc', 'column_name' => 'ipcr.last_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_main_group' => array('entity_name'=>'ipc', 'column_name' => 'ipcs.ipc_main_group', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_section' => array('entity_name'=>'ipc', 'column_name' => 'ipcs.ipc_section', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_sequence' => array('entity_name'=>'ipc', 'column_name' => 'ipcs.ipc_sequence', 'datatype' => 'int', 'query' => 'n', 'sort' => 'suppl'),
    'ipc_subclass' => array('entity_name'=>'ipc', 'column_name' => 'ipcs.ipc_subclass', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_subgroup' => array('entity_name'=>'ipc', 'column_name' => 'ipcs.ipc_subgroup', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_symbol_position' => array('entity_name'=>'ipc', 'column_name' => 'ipcs.ipc_symbol_position', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_total_num_assignees' => array('entity_name'=>'ipc', 'column_name' => 'ipcs.ipc_total_num_assignees', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_total_num_inventors' => array('entity_name'=>'ipc', 'column_name' => 'ipcs.ipc_total_num_inventors', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'ipc_version_indicator' => array('entity_name'=>'ipc', 'column_name' => 'ipcs.ipc_version_indicator', 'datatype' => 'date', 'query' => 'n', 'sort' => 'suppl'),
    'nber_category_id' => array('entity_name'=>'nber', 'column_name' => 'nbers.nber_category_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'nber_category_title' => array('entity_name'=>'nber', 'column_name' => 'nbers.nber_category_title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'nber_first_seen_date' => array('entity_name' => 'nber', 'column_name' => 'nber_subcategory.first_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'y'),
    'nber_last_seen_date' => array('entity_name' => 'nber', 'column_name' => 'nber_subcategory.last_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'y'),
    'nber_subcategory_id' => array('entity_name'=>'nber', 'column_name' => 'nbers.nber_subcategory_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'nber_subcategory_title' => array('entity_name'=>'nber', 'column_name' => 'nbers.nber_subcategory_title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'nber_total_num_assignees' => array('entity_name'=>'nber', 'column_name' => 'nbers.nber_total_num_assignees', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'nber_total_num_inventors' => array('entity_name'=>'nber', 'column_name' => 'nbers.nber_total_num_inventors', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'nber_total_num_patents' => array('entity_name'=>'nber', 'column_name' => 'nbers.nber_total_num_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'patent_abstract' => array('entity_name'=>'patent', 'column_name' => 'patent_abstract', 'datatype' => 'fulltext', 'query' => 'y', 'sort' => 'suppl'),
    'patent_date' => array('entity_name'=>'patent', 'column_name' => 'patent_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'y'),
    'patent_firstnamed_assignee_id' => array('entity_name'=>'patent', 'column_name' => 'patent_firstnamed_assignee_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'patent_firstnamed_assignee_city' => array('entity_name'=>'patent', 'column_name' => 'patent_firstnamed_assignee_city', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'patent_firstnamed_assignee_country' => array('entity_name'=>'patent', 'column_name' => 'patent_firstnamed_assignee_country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'patent_firstnamed_assignee_latitude' => array('entity_name'=>'patent', 'column_name' => 'patent_firstnamed_assignee_latitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'y'),
    'patent_firstnamed_assignee_location_id' => array('entity_name'=>'patent', 'column_name' => 'patent_firstnamed_assignee_location_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'patent_firstnamed_assignee_longitude' => array('entity_name'=>'patent', 'column_name' => 'patent_firstnamed_assignee_longitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'y'),
    'patent_firstnamed_assignee_state' => array('entity_name'=>'patent', 'column_name' => 'patent_firstnamed_assignee_state', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'patent_firstnamed_inventor_id' => array('entity_name'=>'patent', 'column_name' => 'patent_firstnamed_inventor_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'patent_firstnamed_inventor_city' => array('entity_name'=>'patent', 'column_name' => 'patent_firstnamed_inventor_city', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'patent_firstnamed_inventor_country' => array('entity_name'=>'patent', 'column_name' => 'patent_firstnamed_inventor_country', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'patent_firstnamed_inventor_latitude' => array('entity_name'=>'patent', 'column_name' => 'patent_firstnamed_inventor_latitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'y'),
    'patent_firstnamed_inventor_location_id' => array('entity_name'=>'patent', 'column_name' => 'patent_firstnamed_inventor_location_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'patent_firstnamed_inventor_longitude' => array('entity_name'=>'patent', 'column_name' => 'patent_firstnamed_inventor_longitude', 'datatype' => 'float', 'query' => 'n', 'sort' => 'y'),
    'patent_firstnamed_inventor_state' => array('entity_name'=>'patent', 'column_name' => 'patent_firstnamed_inventor_state', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'patent_id' => array('entity_name'=>'patent', 'column_name' => 'patent_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'patent_kind' => array('entity_name'=>'patent', 'column_name' => 'patent_kind', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'patent_num_cited_by_us_patents' => array('entity_name'=>'patent', 'column_name' => 'patent_num_cited_by_us_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'patent_num_combined_citations' => array('entity_name'=>'patent', 'column_name' => 'patent_num_combined_citations', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'patent_num_foreign_citations' => array('entity_name'=>'patent', 'column_name' => 'patent_num_foreign_citations', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'patent_num_us_application_citations' => array('entity_name'=>'patent', 'column_name' => 'patent_num_us_application_citations', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'patent_num_us_patent_citations' => array('entity_name'=>'patent', 'column_name' => 'patent_num_us_patent_citations', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'patent_num_claims' => array('entity_name'=>'patent', 'column_name' => 'patent_num_claims', 'datatype' => 'int', 'query' => 'n', 'sort' => 'y'),
    'patent_number' => array('entity_name'=>'patent', 'column_name' => 'patent_number', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'patent_average_processing_time' => array('entity_name'=>'patent', 'column_name' => 'patent_average_processing_time', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'patent_processing_time' => array('entity_name'=>'patent', 'column_name' => 'patent_processing_time', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'patent_title' => array('entity_name'=>'patent', 'column_name' => 'patent_title', 'datatype' => 'fulltext', 'query' => 'y', 'sort' => 'y'),
    'patent_type' => array('entity_name'=>'patent', 'column_name' => 'patent_type', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'patent_year' => array('entity_name'=>'patent', 'column_name' => 'patent_year', 'datatype' => 'int', 'query' => 'y', 'sort' => 'y'),
    'rawinventor_first_name' => array('entity_name'=>'rawinventor', 'column_name' => 'rawinventors.rawinventor_first_name', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),
    'rawinventor_last_name' => array('entity_name'=>'rawinventor', 'column_name' => 'rawinventors.rawinventor_last_name', 'datatype' => 'string', 'query' => 'y', 'sort' => 'y'),

    'uspc_first_seen_date' => array('entity_name' => 'uspc', 'column_name' => 'uspc_mainclass.first_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_last_seen_date' => array('entity_name' => 'uspc', 'column_name' => 'uspc_mainclass.last_seen_date', 'datatype' => 'date', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_mainclass_id' => array('entity_name'=>'uspc', 'column_name' => 'uspcs.uspc_mainclass_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_mainclass_title' => array('entity_name'=>'uspc', 'column_name' => 'uspcs.uspc_mainclass_title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_sequence' => array('entity_name'=>'uspc', 'column_name' => 'uspcs.uspc_sequence', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_subclass_id' => array('entity_name'=>'uspc', 'column_name' => 'uspcs.uspc_subclass_id', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_subclass_title' => array('entity_name'=>'uspc', 'column_name' => 'uspcs.uspc_subclass_title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_total_num_assignees' => array('entity_name'=>'uspc', 'column_name' => 'uspcs.uspc_total_num_assignees', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_total_num_inventors' => array('entity_name'=>'uspc', 'column_name' => 'uspcs.uspc_total_num_inventors', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'uspc_total_num_patents' => array('entity_name'=>'uspc', 'column_name' => 'uspcs.uspc_total_num_patents', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'wipo_field_id' => array('entity_name'=>'wipo', 'column_name' => 'wipos.wipo_field_id', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl'),
    'wipo_field_title' => array('entity_name'=>'wipo', 'column_name' => 'wipos.wipo_field_title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'wipo_sector_title' => array('entity_name'=>'wipo', 'column_name' => 'wipos.wipo_sector_title', 'datatype' => 'string', 'query' => 'y', 'sort' => 'suppl'),
    'wipo_sequence' => array('entity_name'=>'wipo', 'column_name' => 'wipos.wipo_sequence', 'datatype' => 'int', 'query' => 'y', 'sort' => 'suppl')
);



 $fp = fopen('solr-patent-entity-specs.json', 'w');
                fwrite($fp, json_encode($PATENT_ENTITY_SPECS));
                fclose($fp);

 $fp = fopen('solr-patent-field-specs.json', 'w');
                fwrite($fp, json_encode($PATENT_FIELD_SPECS));
                fclose($fp);

 ?>